name: demo on-push

on:
  push:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: fail this action randomly
      run: |
        num=`shuf -i 0-1 -n 1`
        echo $num
        if [ "$num" == 1 ]; then
          exit 1
        else
          echo "No failure today."
        fi