name: demo on-push

on: push
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world! This job was automatically triggered by a ${{ github.event_name }} event."