name: demo on-push

on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Time to fail this action
      run: exit 1